core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('auth_app.urls')),
                  path('', include('dashboard_app.urls')),
                  path('', include('hr_app.urls')),
                  path('', include('inventory_app.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

inventory_app/urls.py
from django.urls import path
from .views import (
    SupplierCRUDView, SupplierDataView,
    SupplierDeleteView, LocationCRUDView,
    LocationDataView, LocationDeleteView,
    ItemCategoryCRUDView, ItemCategoryDataView, ItemCategoryDeleteView,
    ItemSubcategoryCRUDView, ItemSubcategoryDataView, ItemSubcategoryDeleteView,
    ItemCRUDView, ItemDataView, ItemDeleteView, LoadItemSubcategoriesView, EquipmentCategoryCRUDView,
    EquipmentCategoryDataView, EquipmentCategoryDeleteView, EquipmentSubcategoryCRUDView, EquipmentSubcategoryDataView,
    EquipmentSubcategoryDeleteView, EquipmentCRUDView, EquipmentDataView, EquipmentDeleteView,
    LoadEquipmentSubcategoriesView, PurchaseOrderCreateView, PurchaseOrderDataView, PurchaseOrderItemDataView,
    ApprovePurchaseOrderView, PurchaseOrderUpdateView, ItemRequisitionCreateView, DraftRequisitionDataView,
    ItemRequisitionUpdateView, SubmittedRequisitionDataView, GeneratePDFView, DraftRequisitionDetailView,
    DraftToSubmittedView, SubmittedRequisitionDetailView, ManageStoreRequisitionOrderView,
    ManagePurchaseRequisitionOrderView, GetCategoriesView, GetSubcategoriesView, GetSuppliersView,
    GeneratePurchasePDFView, ApprovedRequisitionDataView, RejectedRequisitionDataView, DepartmentItemQuantityView,
    OrderPageView, OrderDataView, OrderPurchaseDataView, UnderReviewRequisitionDataView, UnderReviewRequisitionDetailView

)

app_name = 'inventory_app'

urlpatterns = [
    # Supplier
    path('suppliers/', SupplierCRUDView.as_view(), name='supplier'),
    path('ajax_datatable/supplier/', SupplierDataView.as_view(), name='supplier_data'),
    path('supplier/delete/', SupplierDeleteView.as_view(), name='supplier_delete'),

    path('get_suppliers/', GetSuppliersView.as_view(), name='get_suppliers'),

    # Location
    path('warehouse/', LocationCRUDView.as_view(), name='location'),
    path('ajax_datatable/location/', LocationDataView.as_view(), name='location_data'),
    path('location/delete/', LocationDeleteView.as_view(), name='location_delete'),

    # ItemCategory
    path('item_categories/', ItemCategoryCRUDView.as_view(), name='item_category'),
    path('ajax_datatable/item_category/', ItemCategoryDataView.as_view(), name='item_category_data'),
    path('item_category/delete/', ItemCategoryDeleteView.as_view(), name='item_category_delete'),

    path('get_categories/', GetCategoriesView.as_view(), name='get_categories'),

    # ItemSubcategory
    path('item_subcategories/', ItemSubcategoryCRUDView.as_view(), name='item_subcategory'),
    path('ajax_datatable/item_subcategory/', ItemSubcategoryDataView.as_view(), name='item_subcategory_data'),
    path('item_subcategory/delete/', ItemSubcategoryDeleteView.as_view(), name='item_subcategory_delete'),

    path('get_subcategories/', GetSubcategoriesView.as_view(), name='get_subcategories'),

    # Item
    path('items/', ItemCRUDView.as_view(), name='item'),
    path('ajax_datatable/item/', ItemDataView.as_view(), name='item_data'),
    path('item/delete/', ItemDeleteView.as_view(), name='item_delete'),

    # Item Dependent chain
    path('ajax/load-item-subcategories/', LoadItemSubcategoriesView.as_view(), name='ajax_load_item_subcategories'),

    # EquipmentCategory
    path('equipment_categories/', EquipmentCategoryCRUDView.as_view(), name='equipment_category'),
    path('ajax_datatable/equipment_category/', EquipmentCategoryDataView.as_view(), name='equipment_category_data'),
    path('equipment_category/delete/', EquipmentCategoryDeleteView.as_view(), name='equipment_category_delete'),

    # EquipmentSubcategory
    path('equipment_subcategories/', EquipmentSubcategoryCRUDView.as_view(), name='equipment_subcategory'),
    path('ajax_datatable/equipment_subcategory/', EquipmentSubcategoryDataView.as_view(),
         name='equipment_subcategory_data'),
    path('equipment_subcategory/delete/', EquipmentSubcategoryDeleteView.as_view(),
         name='equipment_subcategory_delete'),

    # Equipment
    path('equipment/', EquipmentCRUDView.as_view(), name='equipment'),
    path('ajax_datatable/equipment/', EquipmentDataView.as_view(), name='equipment_data'),
    path('equipment/delete/', EquipmentDeleteView.as_view(), name='equipment_delete'),

    # Equipment Dependent chain
    path('ajax/load-equipment-subcategories/', LoadEquipmentSubcategoriesView.as_view(),
         name='ajax_load_equipment_subcategories'),

    # *****************************************************************************
    # ITEM REQUISITION
    # *****************************************************************************

    path('requisition_order/new/', ItemRequisitionCreateView.as_view(), name='requisition_order_new'),

    # Ajax Tables
    path('ajax_datatable/requisitions/draft/', DraftRequisitionDataView.as_view(), name='draft_requisition_data'),
    path('ajax_datatable/requisitions/submitted/', SubmittedRequisitionDataView.as_view(),
         name='submitted_requisition_data'),
    path('ajax_datatable/requisitions/under-review/', UnderReviewRequisitionDataView.as_view(),
         name='under-review_requisition_data'),
    path('ajax_datatable/requisitions/approved/', ApprovedRequisitionDataView.as_view(),
         name='processed_requisition_data'),
    path('ajax_datatable/requisitions/rejected/', RejectedRequisitionDataView.as_view(),
         name='rejected_requisition_data'),

    path('requisition_order/edit/<int:id>/', ItemRequisitionUpdateView.as_view(), name='requisition_order_edit'),

    # PDF
    path('generate_preview_purchase/<int:requisition_id>/', GeneratePurchasePDFView.as_view(),
         name='generate_preview_purchase'),
    path('generate_preview_store/<int:requisition_id>/', GeneratePurchasePDFView.as_view(),
         name='generate_preview_store'),
    path('generate_preview/<int:requisition_id>/', GeneratePDFView.as_view(), name='generate_preview'),

    # Modals Details
    path('draft_requisitions/<int:pk>/details/', DraftRequisitionDetailView.as_view(),
         name='draft_requisition_details'),
    path('submitted_requisitions/<int:pk>/details/', SubmittedRequisitionDetailView.as_view(),
         name='submitted_requisition_details'),
    path('under-review_requisitions/<int:pk>/details/', UnderReviewRequisitionDetailView.as_view(),
         name='under-review_requisition_details'),

    # Save Draft as Submitted
    path('requisition/<int:id>/submit/', DraftToSubmittedView.as_view(), name='draft_to_submitted'),

    # Manage Store Requisition
    path('store_requisition_order/manage/<int:id>/', ManageStoreRequisitionOrderView.as_view(),
         name='store_requisition_order_manage'),

    # Manage Purchase Requisition
    path('purchase_requisition_order/manage/<int:id>/', ManagePurchaseRequisitionOrderView.as_view(),
         name='purchase_requisition_order_manage'),

    # Department Item Quantity
    path('get_department_item_quantity/', DepartmentItemQuantityView.as_view(), name='get_department_item_quantity'),

    # ORDERS

    path('orders/', OrderPageView.as_view(), name='orders'),
    path('orders/table/', OrderDataView.as_view(), name='orders_table'),
    path('purchase/orders/table/', OrderPurchaseDataView.as_view(), name='purchase_orders_table'),

    # Item Purchase
    path('purchase_order/new/', PurchaseOrderCreateView.as_view(), name='purchase_order_new'),
    path('ajax_datatable/purchased/items/', PurchaseOrderItemDataView.as_view(), name='purchased-item_data'),
    path('ajax_datatable/purchased/orders/', PurchaseOrderDataView.as_view(), name='purchased-order_data'),
    path('purchase_order/<int:id>/approve/', ApprovePurchaseOrderView.as_view(), name='approve_purchase_order'),
    path('purchase_order/edit/<int:id>/', PurchaseOrderUpdateView.as_view(), name='purchase_order_edit'),
]

inventory_app/templates/inventory_app/item/requisition/includes/modals/submitted/modal_body.html
{% load static %}
<div class="card bg-label-secondary p-2">
   <div class="row" style="font-size: 14px; text-transform: uppercase;">
      <div class="col-md-6">
            DATE: <span class="fw-medium" id="requisition_date2">{{ requisition_data.requested_at }}</span><br>
            REFERENCE #: <span class="fw-medium" id="requisitionNumber">{{ requisition_data.requisition_id }}</span>
            <input type="hidden" id="requisitionID">
            <br> TYPE: <span class="text-primary" id="requisition_type">{{ requisition_data.requisition_type }}</span>
            <br> STATUS: <span class="text-primary" id="status">{{ requisition_data.submission_status }}</span>
      </div>
      <div class="col-md-6 text-right order_barcodes ms-auto">
         <img src="{% static 'assets/images/authentication-QR.png' %}" class="float-end" style="width: 76px;">
      </div>
   </div>
</div>

<div class="row mt-2 mb-2">
   <!-- Column 1 - To: Fruits Supply Masters -->
   <div class="col-6">
      <h6>Office/Department:</h6>
      <span class="fw-medium text-success" id="department">{{ requisition_data.sub_department }}</span><br>
      <span id="created_by">{{ requisition_data.requested_by }}</span>
      <br> Tel: <span id="phone_number">{{ requisition_data.phone_number }}</span>
      <br> Email: <span id="email">{{ requisition_data.email }}</span>
   </div>
   <!-- Column 2 - From: Stock Manager Advance -->
   <div class="col-6">
      <h6>{% if requisition_data.requisition_type == 'Store' %}Warehouse/Store{% else %}Supplier/Vendor{% endif %}:</h6>
      <span class="fw-medium text-success" id="warehouse">{{ requisition_data.issuer }}</span><br>
      Address, City <br>
      Tel: 012345678 <br>
      Email: info@dskmedix.com
   </div>
</div>

<!-- Table goes here -->
<table id="{{ requisition_data.requisition_type | lower }}-formset-table" class="table table-bordered table-hover">
    <thead>
  <tr data-item-id="{{ item.id }}">
     <th scope="col">Item Name</th>
     <th scope="col">{% if requisition_data.requisition_type == 'Store' %}Requested Quantity{% else %}Quantity To Purchase{% endif %}</th>
     <th scope="col">Department Quantity</th>
     <th scope="col">Store Quantity</th>
     <th scope="col">Remark</th>
  </tr>
</thead>
<tbody>
  {% for item in requisition_items %}
  <tr>
     <td>{{ item.item_name }} {{ item.strength }}</td>
     <td>{{ item.quantity }}</td>
     <td>{{ item.quantity_in_sub_department }}</td>
     <td>{{ item.quantity_on_hand }}</td>
     <td>{{ item.remark }}</td>
  </tr>
  {% endfor %}
</tbody>
</table>

<div class="row mb-2">
   <div class="col-3 float-start">
      <div class="bg-label-secondary p-2 mt-5">
         Submitted by: <span class="created_by">{{ requisition_data.requested_by }}</span>
         <br> Date: <span id="requisition_date">{{ requisition_data.requested_at }}</span>
         <div class="signature" style="display: none;">
            <p>Signature:</p>
            <hr>
         </div>
      </div>
   </div>
</div>

<div class="row">
   <div class="nav-align-top p-1" style="font-size: 11px; text-transform: uppercase;">
      <div class="col-md-12 text-right">
            <ul class="nav nav-tabs nav-fill" role="tablist">
               {% if requisition_data.submission_status == 'Submitted' %}

                  <!-- Different buttons for Store and Purchase -->
                  {% if requisition_data.requisition_type == 'Store' %}
                        {% if user.is_superuser or user.role.name == 'Admin' or user.role.name == 'Accountant' or user.role.name == 'Procurement Officer' %}
                           <li class="nav-item me-1" id="updateStoreLink">
                              {% if requisition_data.id %}
                                 <a href="{% url 'inventory_app:requisition_order_edit' requisition_data.id %}" id="updateStoreRequisition" class="nav-link active bg-success"> MANAGE </a>
                              {% endif %}
                           </li>

                           <li class="nav-item me-1" id="rejectStoreLink">
                              <button type="button" id="rejectStoreRequisition" class="nav-link active bg-danger" role="tab" data-bs-toggle="tab" aria-controls="navs-justified-new" aria-selected="true"> REJECT </button>
                           </li>
                        {% endif %}

                           <li class="nav-item me-1">
                              {% if requisition_data.id %}
                                 <a href="{% url 'inventory_app:generate_preview_purchase' requisition_data.id %}" target="_blank" id="generateStorePdfButton" type="button" class="nav-link active bg-secondary" role="tab"> GENERATE PDF </a>
                              {% endif %}
                           </li>
                  {% else %}
                        {% if user.is_superuser or user.role.name == 'Admin' or user.role.name == 'Accountant' or user.role.name == 'Procurement Officer' %}
                           <li class="nav-item me-1" id="updateLink">
                              {% if requisition_data.id %}
                                 <a href="{% url 'inventory_app:purchase_requisition_order_manage' requisition_data.id %}" id="updateRequisition" class="nav-link active bg-success"> MANAGE </a>
                              {% endif %}
                           </li>

                           <li class="nav-item me-1" id="rejectLink">
                              <button type="button" id="rejectRequisition" class="nav-link active bg-danger" role="tab" data-bs-toggle="tab" aria-controls="navs-justified-new" aria-selected="true"> REJECT </button>
                           </li>
                        {% endif %}
                           <li class="nav-item me-1">
                              {% if requisition_data.id %}
                                 <a href="{% url 'inventory_app:generate_preview_purchase' requisition_data.id %}" target="_blank" id="generatePdfButton" type="button" class="nav-link active bg-secondary" role="tab"> GENERATE PDF </a>
                              {% endif %}
                           </li>
                  {% endif %}
                  <!-- Common buttons for both Store and Purchase -->
                  <li class="nav-item" id="closeNav">
                        <button type="button" id="closeButton" class="nav-link active bg-secondary" role="tab" data-bs-toggle="tab" data-bs-dismiss="modal" aria-controls="navs-justified-new" aria-selected="true"> CLOSE </button>
                  </li>
               {% endif %}
            </ul>
      </div>
   </div>
   <!--End buttons-->
</div>