core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('auth_app.urls')),
                  path('', include('dashboard_app.urls')),
                  path('', include('hr_app.urls')),
                  path('', include('inventory_app.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

inventory_app/urls.py
from django.urls import path
from .views import (
    SupplierCRUDView, SupplierDataView,
    SupplierDeleteView, LocationCRUDView,
    LocationDataView, LocationDeleteView,
    ItemCategoryCRUDView, ItemCategoryDataView, ItemCategoryDeleteView,
    ItemSubcategoryCRUDView, ItemSubcategoryDataView, ItemSubcategoryDeleteView,
    ItemCRUDView, ItemDataView, ItemDeleteView, LoadItemSubcategoriesView, EquipmentCategoryCRUDView,
    EquipmentCategoryDataView, EquipmentCategoryDeleteView, EquipmentSubcategoryCRUDView, EquipmentSubcategoryDataView,
    EquipmentSubcategoryDeleteView, EquipmentCRUDView, EquipmentDataView, EquipmentDeleteView,
    LoadEquipmentSubcategoriesView, PurchaseOrderCreateView, PurchaseOrderDataView, PurchaseOrderItemDataView,
    ApprovePurchaseOrderView, PurchaseOrderUpdateView, ItemRequisitionCreateView, DraftRequisitionDataView,
    ItemRequisitionUpdateView, SubmittedRequisitionDataView, GeneratePDFView, DraftRequisitionDetailView,
    DraftToSubmittedView, SubmittedRequisitionDetailView, ManageStoreRequisitionOrderView,
    ManagePurchaseRequisitionOrderView, GetCategoriesView, GetSubcategoriesView, GetSuppliersView,
    GeneratePurchasePDFView, ApprovedRequisitionDataView, RejectedRequisitionDataView, DepartmentItemQuantityView,
    OrderPageView, OrderDataView, OrderPurchaseDataView, UnderReviewRequisitionDataView, UnderReviewRequisitionDetailView

)

app_name = 'inventory_app'

urlpatterns = [
    # Supplier
    path('suppliers/', SupplierCRUDView.as_view(), name='supplier'),
    path('ajax_datatable/supplier/', SupplierDataView.as_view(), name='supplier_data'),
    path('supplier/delete/', SupplierDeleteView.as_view(), name='supplier_delete'),

    path('get_suppliers/', GetSuppliersView.as_view(), name='get_suppliers'),

    # Location
    path('warehouse/', LocationCRUDView.as_view(), name='location'),
    path('ajax_datatable/location/', LocationDataView.as_view(), name='location_data'),
    path('location/delete/', LocationDeleteView.as_view(), name='location_delete'),

    # ItemCategory
    path('item_categories/', ItemCategoryCRUDView.as_view(), name='item_category'),
    path('ajax_datatable/item_category/', ItemCategoryDataView.as_view(), name='item_category_data'),
    path('item_category/delete/', ItemCategoryDeleteView.as_view(), name='item_category_delete'),

    path('get_categories/', GetCategoriesView.as_view(), name='get_categories'),

    # ItemSubcategory
    path('item_subcategories/', ItemSubcategoryCRUDView.as_view(), name='item_subcategory'),
    path('ajax_datatable/item_subcategory/', ItemSubcategoryDataView.as_view(), name='item_subcategory_data'),
    path('item_subcategory/delete/', ItemSubcategoryDeleteView.as_view(), name='item_subcategory_delete'),

    path('get_subcategories/', GetSubcategoriesView.as_view(), name='get_subcategories'),

    # Item
    path('items/', ItemCRUDView.as_view(), name='item'),
    path('ajax_datatable/item/', ItemDataView.as_view(), name='item_data'),
    path('item/delete/', ItemDeleteView.as_view(), name='item_delete'),

    # Item Dependent chain
    path('ajax/load-item-subcategories/', LoadItemSubcategoriesView.as_view(), name='ajax_load_item_subcategories'),

    # EquipmentCategory
    path('equipment_categories/', EquipmentCategoryCRUDView.as_view(), name='equipment_category'),
    path('ajax_datatable/equipment_category/', EquipmentCategoryDataView.as_view(), name='equipment_category_data'),
    path('equipment_category/delete/', EquipmentCategoryDeleteView.as_view(), name='equipment_category_delete'),

    # EquipmentSubcategory
    path('equipment_subcategories/', EquipmentSubcategoryCRUDView.as_view(), name='equipment_subcategory'),
    path('ajax_datatable/equipment_subcategory/', EquipmentSubcategoryDataView.as_view(),
         name='equipment_subcategory_data'),
    path('equipment_subcategory/delete/', EquipmentSubcategoryDeleteView.as_view(),
         name='equipment_subcategory_delete'),

    # Equipment
    path('equipment/', EquipmentCRUDView.as_view(), name='equipment'),
    path('ajax_datatable/equipment/', EquipmentDataView.as_view(), name='equipment_data'),
    path('equipment/delete/', EquipmentDeleteView.as_view(), name='equipment_delete'),

    # Equipment Dependent chain
    path('ajax/load-equipment-subcategories/', LoadEquipmentSubcategoriesView.as_view(),
         name='ajax_load_equipment_subcategories'),

    # *****************************************************************************
    # ITEM REQUISITION
    # *****************************************************************************

    path('requisition_order/new/', ItemRequisitionCreateView.as_view(), name='requisition_order_new'),

    # Ajax Tables
    path('ajax_datatable/requisitions/draft/', DraftRequisitionDataView.as_view(), name='draft_requisition_data'),
    path('ajax_datatable/requisitions/submitted/', SubmittedRequisitionDataView.as_view(),
         name='submitted_requisition_data'),
    path('ajax_datatable/requisitions/under-review/', UnderReviewRequisitionDataView.as_view(),
         name='under-review_requisition_data'),
    path('ajax_datatable/requisitions/approved/', ApprovedRequisitionDataView.as_view(),
         name='processed_requisition_data'),
    path('ajax_datatable/requisitions/rejected/', RejectedRequisitionDataView.as_view(),
         name='rejected_requisition_data'),

    path('requisition_order/edit/<int:id>/', ItemRequisitionUpdateView.as_view(), name='requisition_order_edit'),

    # PDF
    path('generate_preview_purchase/<int:requisition_id>/', GeneratePurchasePDFView.as_view(),
         name='generate_preview_purchase'),
    path('generate_preview_store/<int:requisition_id>/', GeneratePurchasePDFView.as_view(),
         name='generate_preview_store'),
    path('generate_preview/<int:requisition_id>/', GeneratePDFView.as_view(), name='generate_preview'),

    # Modals Details
    path('draft_requisitions/<int:pk>/details/', DraftRequisitionDetailView.as_view(),
         name='draft_requisition_details'),
    path('submitted_requisitions/<int:pk>/details/', SubmittedRequisitionDetailView.as_view(),
         name='submitted_requisition_details'),
    path('under-review_requisitions/<int:pk>/details/', UnderReviewRequisitionDetailView.as_view(),
         name='under-review_requisition_details'),

    # Save Draft as Submitted
    path('requisition/<int:id>/submit/', DraftToSubmittedView.as_view(), name='draft_to_submitted'),

    # Manage Store Requisition
    path('store_requisition_order/manage/<int:id>/', ManageStoreRequisitionOrderView.as_view(),
         name='store_requisition_order_manage'),

    # Manage Purchase Requisition
    path('purchase_requisition_order/manage/<int:id>/', ManagePurchaseRequisitionOrderView.as_view(),
         name='purchase_requisition_order_manage'),

    # Department Item Quantity
    path('get_department_item_quantity/', DepartmentItemQuantityView.as_view(), name='get_department_item_quantity'),

    # ORDERS

    path('orders/', OrderPageView.as_view(), name='orders'),
    path('orders/table/', OrderDataView.as_view(), name='orders_table'),
    path('purchase/orders/table/', OrderPurchaseDataView.as_view(), name='purchase_orders_table'),

    # Item Purchase
    path('purchase_order/new/', PurchaseOrderCreateView.as_view(), name='purchase_order_new'),
    path('ajax_datatable/purchased/items/', PurchaseOrderItemDataView.as_view(), name='purchased-item_data'),
    path('ajax_datatable/purchased/orders/', PurchaseOrderDataView.as_view(), name='purchased-order_data'),
    path('purchase_order/<int:id>/approve/', ApprovePurchaseOrderView.as_view(), name='approve_purchase_order'),
    path('purchase_order/edit/<int:id>/', PurchaseOrderUpdateView.as_view(), name='purchase_order_edit'),
]

inventory_app/templates/inventory_app/item/purchase/create.html
{% extends "base.html" %}
{% load static %}
{% load widget_tweaks %}
{% block title %} Item Purchase {% endblock title %}

{% block content %}

<div class="d-flex justify-content-between align-items-center flex-wrap mb-4 gap-3">
    <div class="d-flex flex-column">
        <h3>Purchase Order:</h3>
        <p class="text-primary mb-0">Administrator Dashboard</p>
    </div>
    <div class="d-flex justify-content-between align-items-center rounded flex-wrap gap-3">
        <div class="form-check form-switch mb-0 iq-status-switch">
            <input class="form-check-input iq-status" type="checkbox" id="iq-switch" checked="">
            <label class="form-check-label iq-reset-status" for="iq-switch">
                Online
            </label>
        </div>
        <div class="form-group mb-0">
            <select class="select2-basic-single form-control" name="state" style="width: 100%;">
                <option >Past 30 Days</option>
                <option >Past 60 Days</option>
                <option >Past 90 Days</option>
                <option >Past 1 year</option>
                <option >Past 2 year</option>
            </select>
        </div>
        <div class="form-group mb-0">
            <input type="text" name="start" class="form-control range_flatpicker flatpickr-input active" placeholder="24 Jan 2022 to 23 Feb 2022" readonly="readonly">
        </div>
        <button type="button" class="btn btn-primary">Analytics</button>
    </div>
</div>


<div class="container-fluid">

    <div class="mb-5">
        <div class="card-toolbar">
        <a href="{% url 'inventory_app:item_category' %}" id="item-category-page" class="btn btn-sm custom-form-action-button btn-info me-2">Categories</a>
        <a href="{% url 'inventory_app:item_subcategory' %}" id="item-subcategory-page" class="btn btn-sm custom-form-action-button btn-info me-2">Subcategories</a>
        <a href="{% url 'inventory_app:item' %}" id="item-page" class="btn btn-sm custom-form-action-button btn-primary me-2">Items</a>
        </div>
    </div>

    <div class="card card-block card-stretch card-height" style="min-height: 330px;">
            <nav class="tab-bottom-bordered">
                <div class="mb-0 nav nav-tabs justify-content-around" id="nav-tab1" role="tablist">
                    <button class="nav-link nav-link-view-po py-3 active" id="nav-view-po-11-tab" data-bs-toggle="tab" data-bs-target="#nav-view-po-11" type="button" role="tab" aria-controls="nav-view-po-11" aria-selected="false" tabindex="-1">Purchase Orders</button>
                    <button class="nav-link nav-link-add py-3" id="nav-add-11-tab" data-bs-toggle="tab" data-bs-target="#nav-add-11" type="button" role="tab" aria-controls="nav-add-11" aria-selected="false" tabindex="-1">Add New Purchase</button>
                    <button class="nav-link nav-link-view-pi py-3" id="nav-view-pi-11-tab" data-bs-toggle="tab" data-bs-target="#nav-view-pi-11" type="button" role="tab" aria-controls="nav-view-pi-11" aria-selected="false" tabindex="-1">Purchased Items</button>
                    <button class="nav-link nav-link-quantity py-3" id="nav-quantity-11-tab" data-bs-toggle="tab" data-bs-target="#nav-quantity-11" type="button" role="tab" aria-controls="nav-quantity-11" aria-selected="true">Drafts</button>
                </div>
            </nav>
        <div class="tab-content iq-tab-fade-up" id="nav-tabContent" >

            <div class="tab-pane fade tab-view-po active show" id="nav-view-po-11" role="tabpanel" aria-labelledby="nav-view-po-11-tab">

                <div class="card-body">
                  {% include 'inventory_app/item/purchase/includes/po-table.html' %}
                </div>

            </div>
            <div class="tab-pane fade tab-purchase-item" id="nav-add-11" role="tabpanel" aria-labelledby="nav-add-11-tab">
                <div class="card-body">
                  {% include 'inventory_app/item/purchase/includes/add_form.html' %}
                </div>

            </div>
            <div class="tab-pane fade tab-view-pi" id="nav-view-pi-11" role="tabpanel" aria-labelledby="nav-view-pi-11-tab">
                <div class="card-body">
                  {% include 'inventory_app/item/purchase/includes/pi-table.html' %}
                </div>

            </div>
            <div class="tab-pane fade tab-quantity-item active show" id="nav-quantity-11" role="tabpanel" aria-labelledby="nav-quantity-11-tab">

            </div>
        </div>
    </div>

</div>

{% endblock content %}



{% block extrajs %}

<script>
$(document).ready(function() {
    // Check if the user is a superuser
    var is_superuser = {{ is_superuser|yesno:"true,false" }};

    if (!is_superuser) {
        // Replace this with the actual number of draft orders from your backend
        var num_draft_orders = {{ num_draft_orders }};

        if (num_draft_orders > 0) {
            // Get the "Purchase Form" tab
            var purchaseFormTab = document.getElementById('nav-add-11-tab');

            // Remove the "data-bs-toggle" attribute to prevent the tab from being activated
            purchaseFormTab.removeAttribute('data-bs-toggle');

            // Show an alert when the "Purchase Form" tab is clicked
            purchaseFormTab.addEventListener('click', function(event) {
                event.preventDefault();
                Swal.fire({
                    icon: 'error',
                    title: 'Oops...',
                    text: 'You have ' + num_draft_orders + ' draft order(s). Please complete them before creating a new order.',
                });
            });
        }
    }
});
</script>



<!-- Formset -->
<script src="{% static 'assets/js/apps/inventory_app/item/purchase/add_formset.js' %}"></script>
<script src="{% static 'assets/js/apps/inventory_app/item/purchase/add_form.js' %}"></script>
<script src="{% static 'assets/js/apps/inventory_app/item/purchase/pi_table.js' %}"></script>
<script src="{% static 'assets/js/apps/inventory_app/item/purchase/po_table.js' %}"></script>
{% endblock extrajs %}

inventory_app/templates/inventory_app/item/purchase/edit.html
{% extends "base.html" %}
{% load static %}
{% load widget_tweaks %}
{% block title %} Edit Purchase {% endblock title %}

{% block content %}

<div class="d-flex justify-content-between align-items-center flex-wrap mb-4 gap-3">
    <div class="d-flex flex-column">
        <h3>Purchase Order:</h3>
        <p class="text-primary mb-0">Administrator Dashboard</p>
    </div>
    <div class="d-flex justify-content-between align-items-center rounded flex-wrap gap-3">
        <div class="form-check form-switch mb-0 iq-status-switch">
            <input class="form-check-input iq-status" type="checkbox" id="iq-switch" checked="">
            <label class="form-check-label iq-reset-status" for="iq-switch">
                Online
            </label>
        </div>
        <div class="form-group mb-0">
            <select class="select2-basic-single form-control" name="state" style="width: 100%;">
                <option >Past 30 Days</option>
                <option >Past 60 Days</option>
                <option >Past 90 Days</option>
                <option >Past 1 year</option>
                <option >Past 2 year</option>
            </select>
        </div>
        <div class="form-group mb-0">
            <input type="text" name="start" class="form-control range_flatpicker flatpickr-input active" placeholder="24 Jan 2022 to 23 Feb 2022" readonly="readonly">
        </div>
        <button type="button" class="btn btn-primary">Analytics</button>
    </div>
</div>


<div class="container-fluid">

    <div class="mb-5">
        <div class="card-toolbar">
        <a href="{% url 'inventory_app:purchase_order_new' %}" class="btn btn-sm custom-form-action-button btn-info me-2">Go Back</a>
        </div>
    </div>

    <div class="card card-block card-stretch card-height" style="min-height: 330px;">
        <div class="card-body">
          {% include 'inventory_app/item/purchase/includes/edit_form.html' %}
        </div>
    </div>

</div>

{% endblock content %}



{% block extrajs %}
<!-- Formset -->
<script src="{% static 'assets/js/apps/inventory_app/item/purchase/edit_formset.js' %}"></script>
<!--<script src="{% static 'assets/js/apps/inventory_app/item/purchase/edit_form.js' %}"></script>-->
<script src="{% static 'assets/js/apps/inventory_app/item/purchase/update_form.js' %}"></script>
{% endblock extrajs %}