core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('auth_app.urls')),
                  path('', include('dashboard_app.urls')),
                  path('', include('hr_app.urls')),
                  path('', include('inventory_app.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboard_app/urls.py
from django.urls import path
from .views import DashboardView


app_name = 'dashboard_app'

urlpatterns = [

    path('dashboard/', DashboardView.as_view(), name='dashboard'),

]

inventory_app/urls.py
from django.urls import path
from .views import (
    SupplierCRUDView, SupplierDataView,
    SupplierDeleteView, LocationCRUDView,
    LocationDataView, LocationDeleteView,
    ItemCategoryCRUDView, ItemCategoryDataView, ItemCategoryDeleteView,
    ItemSubcategoryCRUDView, ItemSubcategoryDataView, ItemSubcategoryDeleteView,
    ItemCRUDView, ItemDataView, ItemDeleteView, LoadItemSubcategoriesView, EquipmentCategoryCRUDView,
    EquipmentCategoryDataView, EquipmentCategoryDeleteView, EquipmentSubcategoryCRUDView, EquipmentSubcategoryDataView,
    EquipmentSubcategoryDeleteView, EquipmentCRUDView, EquipmentDataView, EquipmentDeleteView,
    LoadEquipmentSubcategoriesView, PurchaseOrderCreateView, PurchaseOrderDataView, PurchaseOrderItemDataView,
    ApprovePurchaseOrderView, PurchaseOrderUpdateView, ItemRequisitionCreateView, DraftRequisitionDataView,
    ItemRequisitionUpdateView, SubmittedRequisitionDataView, GeneratePDFView, DraftRequisitionDetailView,
    DraftToSubmittedView, SubmittedRequisitionDetailView, ManageStoreRequisitionOrderView,
    ManagePurchaseRequisitionOrderView, GetCategoriesView, GetSubcategoriesView, GetSuppliersView,
    GeneratePurchasePDFView, ApprovedRequisitionDataView, RejectedRequisitionDataView, DepartmentItemQuantityView,
    OrderPageView, OrderDataView, OrderPurchaseDataView, UnderReviewRequisitionDataView, UnderReviewRequisitionDetailView

)

app_name = 'inventory_app'

urlpatterns = [
    # Supplier
    path('suppliers/', SupplierCRUDView.as_view(), name='supplier'),
    path('ajax_datatable/supplier/', SupplierDataView.as_view(), name='supplier_data'),
    path('supplier/delete/', SupplierDeleteView.as_view(), name='supplier_delete'),

    path('get_suppliers/', GetSuppliersView.as_view(), name='get_suppliers'),

    # Location
    path('warehouse/', LocationCRUDView.as_view(), name='location'),
    path('ajax_datatable/location/', LocationDataView.as_view(), name='location_data'),
    path('location/delete/', LocationDeleteView.as_view(), name='location_delete'),

    # ItemCategory
    path('item_categories/', ItemCategoryCRUDView.as_view(), name='item_category'),
    path('ajax_datatable/item_category/', ItemCategoryDataView.as_view(), name='item_category_data'),
    path('item_category/delete/', ItemCategoryDeleteView.as_view(), name='item_category_delete'),

    path('get_categories/', GetCategoriesView.as_view(), name='get_categories'),

    # ItemSubcategory
    path('item_subcategories/', ItemSubcategoryCRUDView.as_view(), name='item_subcategory'),
    path('ajax_datatable/item_subcategory/', ItemSubcategoryDataView.as_view(), name='item_subcategory_data'),
    path('item_subcategory/delete/', ItemSubcategoryDeleteView.as_view(), name='item_subcategory_delete'),

    path('get_subcategories/', GetSubcategoriesView.as_view(), name='get_subcategories'),

    # Item
    path('items/', ItemCRUDView.as_view(), name='item'),
    path('ajax_datatable/item/', ItemDataView.as_view(), name='item_data'),
    path('item/delete/', ItemDeleteView.as_view(), name='item_delete'),

    # Item Dependent chain
    path('ajax/load-item-subcategories/', LoadItemSubcategoriesView.as_view(), name='ajax_load_item_subcategories'),

    # EquipmentCategory
    path('equipment_categories/', EquipmentCategoryCRUDView.as_view(), name='equipment_category'),
    path('ajax_datatable/equipment_category/', EquipmentCategoryDataView.as_view(), name='equipment_category_data'),
    path('equipment_category/delete/', EquipmentCategoryDeleteView.as_view(), name='equipment_category_delete'),

    # EquipmentSubcategory
    path('equipment_subcategories/', EquipmentSubcategoryCRUDView.as_view(), name='equipment_subcategory'),
    path('ajax_datatable/equipment_subcategory/', EquipmentSubcategoryDataView.as_view(),
         name='equipment_subcategory_data'),
    path('equipment_subcategory/delete/', EquipmentSubcategoryDeleteView.as_view(),
         name='equipment_subcategory_delete'),

    # Equipment
    path('equipment/', EquipmentCRUDView.as_view(), name='equipment'),
    path('ajax_datatable/equipment/', EquipmentDataView.as_view(), name='equipment_data'),
    path('equipment/delete/', EquipmentDeleteView.as_view(), name='equipment_delete'),

    # Equipment Dependent chain
    path('ajax/load-equipment-subcategories/', LoadEquipmentSubcategoriesView.as_view(),
         name='ajax_load_equipment_subcategories'),

    # *****************************************************************************
    # ITEM REQUISITION
    # *****************************************************************************

    path('requisition_order/new/', ItemRequisitionCreateView.as_view(), name='requisition_order_new'),

    # Ajax Tables
    path('ajax_datatable/requisitions/draft/', DraftRequisitionDataView.as_view(), name='draft_requisition_data'),
    path('ajax_datatable/requisitions/submitted/', SubmittedRequisitionDataView.as_view(),
         name='submitted_requisition_data'),
    path('ajax_datatable/requisitions/under-review/', UnderReviewRequisitionDataView.as_view(),
         name='under-review_requisition_data'),
    path('ajax_datatable/requisitions/approved/', ApprovedRequisitionDataView.as_view(),
         name='processed_requisition_data'),
    path('ajax_datatable/requisitions/rejected/', RejectedRequisitionDataView.as_view(),
         name='rejected_requisition_data'),

    path('requisition_order/edit/<int:id>/', ItemRequisitionUpdateView.as_view(), name='requisition_order_edit'),

    # PDF
    path('generate_preview_purchase/<int:requisition_id>/', GeneratePurchasePDFView.as_view(),
         name='generate_preview_purchase'),
    path('generate_preview_store/<int:requisition_id>/', GeneratePurchasePDFView.as_view(),
         name='generate_preview_store'),
    path('generate_preview/<int:requisition_id>/', GeneratePDFView.as_view(), name='generate_preview'),

    # Modals Details
    path('draft_requisitions/<int:pk>/details/', DraftRequisitionDetailView.as_view(),
         name='draft_requisition_details'),
    path('submitted_requisitions/<int:pk>/details/', SubmittedRequisitionDetailView.as_view(),
         name='submitted_requisition_details'),
    path('under-review_requisitions/<int:pk>/details/', UnderReviewRequisitionDetailView.as_view(),
         name='under-review_requisition_details'),

    # Save Draft as Submitted
    path('requisition/<int:id>/submit/', DraftToSubmittedView.as_view(), name='draft_to_submitted'),

    # Manage Store Requisition
    path('store_requisition_order/manage/<int:id>/', ManageStoreRequisitionOrderView.as_view(),
         name='store_requisition_order_manage'),

    # Manage Purchase Requisition
    path('purchase_requisition_order/manage/<int:id>/', ManagePurchaseRequisitionOrderView.as_view(),
         name='purchase_requisition_order_manage'),

    # Department Item Quantity
    path('get_department_item_quantity/', DepartmentItemQuantityView.as_view(), name='get_department_item_quantity'),

    # ORDERS

    path('orders/', OrderPageView.as_view(), name='orders'),
    path('orders/table/', OrderDataView.as_view(), name='orders_table'),
    path('purchase/orders/table/', OrderPurchaseDataView.as_view(), name='purchase_orders_table'),

    # Item Purchase
    path('purchase_order/new/', PurchaseOrderCreateView.as_view(), name='purchase_order_new'),
    path('ajax_datatable/purchased/items/', PurchaseOrderItemDataView.as_view(), name='purchased-item_data'),
    path('ajax_datatable/purchased/orders/', PurchaseOrderDataView.as_view(), name='purchased-order_data'),
    path('purchase_order/<int:id>/approve/', ApprovePurchaseOrderView.as_view(), name='approve_purchase_order'),
    path('purchase_order/edit/<int:id>/', PurchaseOrderUpdateView.as_view(), name='purchase_order_edit'),
]

hr_app/models.py
from django.db import models
from auth_app.models import AppUser


class Designation(models.Model):
    title = models.CharField(max_length=100, unique=True)
    description = models.CharField(max_length=200)
    status = models.CharField(max_length=50)

    def __str__(self):
        return self.title

    def to_dict(self):
        return {
            'title': self.title,
            'description': self.description,
            'status': self.status,
        }


class JobType(models.Model):
    title = models.CharField(max_length=100, unique=True)
    description = models.CharField(max_length=200)
    status = models.CharField(max_length=50)

    def __str__(self):
        return self.title

    def to_dict(self):
        return {
            'title': self.title,
            'description': self.description,
            'status': self.status,
        }


class DepartmentType(models.Model):
    name = models.CharField(max_length=255)
    code = models.CharField(max_length=50)
    status = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Department(models.Model):
    name = models.CharField(max_length=255)
    code = models.CharField(max_length=50)
    status = models.CharField(max_length=50)
    consultation = models.BooleanField(default=False)
    discharge_approval = models.BooleanField(default=False)

    def __str__(self):
        return self.name

    def to_dict(self):
        return {
            'id': self.id,
            'department': self.name,
            'code': self.code,
            'status': self.status,
            'consultation': self.consultation,
            'discharge_approval_required': self.discharge_approval,
        }


class SubDepartmentMaster(models.Model):
    name = models.CharField(max_length=255)
    department = models.ForeignKey(Department, on_delete=models.CASCADE)
    department_types = models.ManyToManyField(DepartmentType)
    status = models.CharField(max_length=50)

    def __str__(self):
        return self.name


# Now, when you upload a file, it will be saved in a directory named employee_<emp_number> where <emp_number> is the
# emp_number of the Employee instance. def user_directory_path(instance, filename): # file will be uploaded to
# MEDIA_ROOT / employee_<id>/<filename> return 'employee_{0}/{1}'.format(instance.employee.emp_number, filename)

def user_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/staff/files/<employee_id>/<filename>
    return 'staff/files/{0}/{1}'.format(instance.employee.id, filename)


class Employee(models.Model):
    STATUS_CHOICES = [
        ('active', 'Active'),
        ('inactive', 'Inactive'),
        # Add more choices as needed
    ]
    GENDERS = [
        ('M', 'Male'),
        ('F', 'Female'),
    ]
    gender = models.CharField(
        max_length=1,
        choices=GENDERS,
        default='N',
    )
    SALUTATIONS = [
        ('Mr', 'Mr'),
        ('Ms', 'Ms'),
        ('Dr', 'Dr'),
        # add more salutations as needed
    ]
    salutation = models.CharField(
        max_length=2,
        choices=SALUTATIONS,
        default='Mr',
    )
    user = models.OneToOneField(AppUser, on_delete=models.CASCADE)
    emp_number = models.CharField(max_length=100, blank=True, unique=True, null=True)
    qualification = models.CharField(max_length=255)
    licence_number = models.CharField(max_length=100)
    national_id = models.CharField(max_length=255)
    date_of_birth = models.DateField()
    date_joined = models.DateField()
    designation = models.ForeignKey(Designation, on_delete=models.SET_NULL, null=True)
    job_type = models.ForeignKey(JobType, on_delete=models.SET_NULL, null=True)
    department = models.ForeignKey(Department, on_delete=models.SET_NULL, null=True)
    sub_department = models.ForeignKey(SubDepartmentMaster, on_delete=models.SET_NULL, null=True)
    status = models.CharField(max_length=50, choices=STATUS_CHOICES, default='active')

    def __str__(self):
        return f"Profile of {self.user}"

    def full_name(self):
        return f"{self.user.first_name} {self.user.last_name}"


class EmployeeContact(models.Model):
    employee = models.ForeignKey(Employee, on_delete=models.CASCADE, related_name='employeecontact')
    address = models.TextField()
    phone_number = models.CharField(max_length=15)


class EmployeeDocument(models.Model):
    employee = models.ForeignKey(Employee, on_delete=models.CASCADE, related_name='employeedocument')
    document_type = models.CharField(max_length=255)
    file = models.FileField(upload_to=user_directory_path)


class EmployeePhoto(models.Model):
    employee = models.ForeignKey(Employee, on_delete=models.CASCADE, related_name='employeephoto')
    image = models.ImageField(upload_to=user_directory_path, default='media/staff/avatar.jpg')

inventory_app/templates/inventory_app/item/requisition/approve_purchase.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

inventory_app/templates/inventory_app/item/requisition/create.html
{% extends "base.html" %}
{% load static %}
{% load widget_tweaks %}
{% block title %} Item Requisition {% endblock title %}

{% block content %}

<div class="d-flex justify-content-between align-items-center flex-wrap mb-4 gap-3">
  <div class="d-flex flex-column">
    <h3>Item Requisition</h3>
    <p class="text-primary mb-0">Administrator Dashboard</p>
  </div>
  <div class="d-flex justify-content-between align-items-center rounded flex-wrap gap-3">
    <div class="form-check form-switch mb-0 iq-status-switch">
      <input class="form-check-input iq-status" type="checkbox" id="iq-switch" checked="">
      <label class="form-check-label iq-reset-status" for="iq-switch"> Online </label>
    </div>
    <div class="form-group mb-0">
      <select class="select2-basic-single form-control" name="state" style="width: 100%;">
        <option>Past 30 Days</option>
        <option>Past 60 Days</option>
        <option>Past 90 Days</option>
        <option>Past 1 year</option>
        <option>Past 2 year</option>
      </select>
    </div>
    <div class="form-group mb-0">
      <input type="text" name="start" class="form-control range_flatpicker flatpickr-input active" placeholder="24 Jan 2022 to 23 Feb 2022" readonly="readonly">
    </div>
    <button type="button" class="btn btn-primary">Analytics</button>
  </div>
</div>
<div class="container-fluid">
  <div class="mb-5">
    <div class="card-toolbar">
      <a href="{% url 'dashboard_app:dashboard' %}" class="btn btn-sm btn-info me-2">Back To Dashboard</a>
    </div>
  </div>
  <div class="card card-block card-stretch card-height" style="min-height: 330px;">
   <nav class="tab-bottom-bordered">
    <div class="mb-0 nav nav-tabs justify-content-around" id="nav-tab1" role="tablist">
        <button class="nav-link nav-link-add py-3 active" id="nav-add-11-tab" data-bs-toggle="tab" data-bs-target="#nav-add-11" type="button" role="tab" aria-controls="nav-add-11" aria-selected="false" tabindex="-1">Create New</button>
        <button class="nav-link nav-link-draft py-3" id="nav-draft-11-tab" data-bs-toggle="tab" data-bs-target="#nav-draft-11" type="button" role="tab" aria-controls="nav-draft-11" aria-selected="false" tabindex="-1"><span class="badge bg-light me-2">{{ num_draft_requisitions }}</span> Drafts </button>
        <button class="nav-link nav-link-submitted py-3" id="nav-submitted-11-tab" data-bs-toggle="tab" data-bs-target="#nav-submitted-11" type="button" role="tab" aria-controls="nav-submitted-11" aria-selected="false" tabindex="-1"><span class="badge bg-primary me-2">{{ num_submitted_requisitions }}</span> Submitted </button>
        <button class="nav-link nav-link-under-review py-3" id="nav-under-review-11-tab" data-bs-toggle="tab" data-bs-target="#nav-under-review-11" type="button" role="tab" aria-controls="nav-under-review-11" aria-selected="false" tabindex="-1"><span class="badge bg-warning me-2">{{ num_under_review_requisitions }}</span> Under Review </button>
        <button class="nav-link nav-link-approved py-3" id="nav-approved-11-tab" data-bs-toggle="tab" data-bs-target="#nav-approved-11" type="button" role="tab" aria-controls="nav-approved-11" aria-selected="false" tabindex="-1"><span class="badge bg-success me-2">{{ num_approved_requisitions }}</span> Approved </button>
        <button class="nav-link nav-link-rejected py-3" id="nav-rejected-11-tab" data-bs-toggle="tab" data-bs-target="#nav-rejected-11" type="button" role="tab" aria-controls="nav-rejected-11" aria-selected="false" tabindex="-1"><span class="badge bg-danger me-2">{{ num_rejected_requisitions }}</span> Rejected </button>
    </div>
</nav>

    <div class="tab-content iq-tab-fade-up" id="nav-tabContent">
      <!-- Tab for Create New -->
      <div class="tab-pane fade tab-purchase-item active show" id="nav-add-11" role="tabpanel" aria-labelledby="nav-add-11-tab">
        <div class="card-body"> {% include 'inventory_app/item/requisition/includes/forms/add.html' %} </div>
      </div>
      <!-- Tab for Drafts -->
      <div class="tab-pane fade tab-draft" id="nav-draft-11" role="tabpanel" aria-labelledby="nav-draft-11-tab">
        <div class="card-body"> {% include 'inventory_app/item/requisition/includes/tables/draft.html' %} </div>
      </div>
      <!-- Tab for Submitted -->
      <div class="tab-pane fade tab-submitted" id="nav-submitted-11" role="tabpanel" aria-labelledby="nav-submitted-11-tab">
        <div class="card-body"> {% include 'inventory_app/item/requisition/includes/tables/submitted.html' %} </div>
      </div>
      <!-- Tab for Under-Review -->
      <div class="tab-pane fade tab-under-review" id="nav-under-review-11" role="tabpanel" aria-labelledby="nav-under-review-11-tab">
        <div class="card-body"> {% include 'inventory_app/item/requisition/includes/tables/under-review.html' %} </div>
      </div>
      <!-- Tab for Approved -->
      <div class="tab-pane fade" id="nav-approved-11" role="tabpanel" aria-labelledby="nav-approved-11-tab">
        <div class="card-body"> {% include 'inventory_app/item/requisition/includes/tables/approved.html' %} </div>
      </div>
      <!-- Tab for Rejected -->
      <div class="tab-pane fade" id="nav-rejected-11" role="tabpanel" aria-labelledby="nav-rejected-11-tab">
        <div class="card-body"> {% include 'inventory_app/item/requisition/includes/tables/rejected.html' %} </div>
      </div>
    </div>
  </div>
</div>

{% include 'inventory_app/item/requisition/includes/modals/preview_requisition_modal.html'  %}


{% endblock content %}


{% block extrajs %}

<script>
$(document).ready(function() {
    // Check if the user is a superuser
    var is_superuser = {{ is_superuser|yesno:"true,false" }};

    if (!is_superuser) {
        // Replace this with the actual number of draft orders from your backend
        var num_draft_orders = {{ num_draft_orders }};

        if (num_draft_orders > 0) {
            // Get the "Purchase Form" tab
            var purchaseFormTab = document.getElementById('nav-add-11-tab');

            // Remove the "data-bs-toggle" attribute to prevent the tab from being activated
            purchaseFormTab.removeAttribute('data-bs-toggle');

            // Show an alert when the "Purchase Form" tab is clicked
            purchaseFormTab.addEventListener('click', function(event) {
                event.preventDefault();
                Swal.fire({
                    icon: 'error',
                    title: 'Oops...',
                    text: 'You have ' + num_draft_orders + ' draft order(s). Please complete them before creating a new order.',
                });
            });
        }
    }
});
</script>
<script>
    $(document).ready(function() {
    if (!user.is_superuser) {
        $('#id_requested_by').select2().prop('disabled', true);
        $('#id_sub_department').select2().prop('disabled', true);
    }
});
</script>
<script>
    $(document).ready(function() {
    // Function to show or hide fields based on requisition type
    function updateFields() {
        var requisitionType = $('#id_requisition_type').val();
        if (requisitionType == 'store') {
            $('.location-field').show();
            $('.supplier-field').hide();
        } else if (requisitionType == 'purchase') {
            $('.location-field').hide();
            $('.supplier-field').show();
        }
    }

    // Call updateFields when the page loads
    updateFields();

    // Call updateFields whenever the requisition type changes
    $('#id_requisition_type').change(updateFields);
});
</script>
<script type="text/javascript">
    var user_id = "{{ user_id }}";
</script>

<!--Loads item in Item Table and Loads Categories -->
<script src="{% static 'assets/js/apps/inventory_app/item/requisition/load-items-script.js' %}"></script>
<script src="{% static 'assets/js/apps/inventory_app/item/requisition/load-categories-script.js' %}"></script>

<!--Create Form when Click Item or Checkbox -->
<script src="{% static 'assets/js/apps/inventory_app/item/requisition/create-formset-script.js' %}"></script>

<!--Save Draft or Submit ass final -->
<script src="{% static 'assets/js/apps/inventory_app/item/requisition/save-draft-submit.js' %}"></script>

<!--Tables-->
<script src="{% static 'assets/js/apps/inventory_app/item/requisition/table/draft.js' %}"></script>
<script src="{% static 'assets/js/apps/inventory_app/item/requisition/table/submitted.js' %}"></script>
<script src="{% static 'assets/js/apps/inventory_app/item/requisition/table/under-review.js' %}"></script>
<script src="{% static 'assets/js/apps/inventory_app/item/requisition/table/pending.js' %}"></script>
<script src="{% static 'assets/js/apps/inventory_app/item/requisition/table/approved.js' %}"></script>
<script src="{% static 'assets/js/apps/inventory_app/item/requisition/table/rejected.js' %}"></script>

<!--Deatils of Requisition in Modals-->
<script src="{% static 'assets/js/apps/inventory_app/item/requisition/modals/draft_requisition_details.js' %}"></script>
<script src="{% static 'assets/js/apps/inventory_app/item/requisition/modals/submitted_requisition_details.js' %}"></script>
<script src="{% static 'assets/js/apps/inventory_app/item/requisition/modals/under-review_requisition_details.js' %}"></script>

<script src="{% static 'assets/js/apps/inventory_app/item/requisition/modals/draft_to_submitted.js' %}"></script>

{% endblock extrajs %}

inventory_app/templates/inventory_app/item/requisition/update.html
{% extends "base.html" %}
{% load static %}
{% load widget_tweaks %}
{% block title %} Edit Requisition {% endblock title %}

{% block content %}

<div class="d-flex justify-content-between align-items-center flex-wrap mb-4 gap-3">
    <div class="d-flex flex-column">
        <h3>Edit Requisition</h3>
        <p class="text-primary mb-0">Administrator Dashboard</p>
    </div>
    <div class="d-flex justify-content-between align-items-center rounded flex-wrap gap-3">
        <div class="form-check form-switch mb-0 iq-status-switch">
            <input class="form-check-input iq-status" type="checkbox" id="iq-switch" checked="">
            <label class="form-check-label iq-reset-status" for="iq-switch">
                Online
            </label>
        </div>
        <div class="form-group mb-0">
            <select class="select2-basic-single form-control" name="state" style="width: 100%;">
                <option >Past 30 Days</option>
                <option >Past 60 Days</option>
                <option >Past 90 Days</option>
                <option >Past 1 year</option>
                <option >Past 2 year</option>
            </select>
        </div>
        <div class="form-group mb-0">
            <input type="text" name="start" class="form-control range_flatpicker flatpickr-input active" placeholder="24 Jan 2022 to 23 Feb 2022" readonly="readonly">
        </div>
        <button type="button" class="btn btn-primary">Analytics</button>
    </div>
</div>


<div class="container-fluid">

    <div class="mb-5">
        <div class="card-toolbar">
        <a href="{% url 'inventory_app:requisition_order_new' %}" class="btn btn-sm custom-form-action-button btn-info me-2">Go Back</a>
        </div>
    </div>

    <div class="card card-block card-stretch card-height" style="min-height: 330px;">
        <div class="card-body">
          {% include 'inventory_app/item/requisition/includes/forms/update.html' %}
        </div>
    </div>

</div>
{% endblock content %}



{% block extrajs %}

<script>
$(document).ready(function() {
    // Check if the user is a superuser
    var is_superuser = {{ is_superuser|yesno:"true,false" }};

    if (!is_superuser) {
        // Replace this with the actual number of draft orders from your backend
        var num_draft_orders = {{ num_draft_orders }};

        if (num_draft_orders > 0) {
            // Get the "Purchase Form" tab
            var purchaseFormTab = document.getElementById('nav-add-11-tab');

            // Remove the "data-bs-toggle" attribute to prevent the tab from being activated
            purchaseFormTab.removeAttribute('data-bs-toggle');

            // Show an alert when the "Purchase Form" tab is clicked
            purchaseFormTab.addEventListener('click', function(event) {
                event.preventDefault();
                Swal.fire({
                    icon: 'error',
                    title: 'Oops...',
                    text: 'You have ' + num_draft_orders + ' draft order(s). Please complete them before creating a new order.',
                });
            });
        }
    }
});
</script>
<script>
    $(document).ready(function() {
    if (!user.is_superuser) {
        $('#id_requested_by').select2().prop('disabled', true);
        $('#id_sub_department').select2().prop('disabled', true);
    }
});
</script>
<script>
    $(document).ready(function() {
    // Function to show or hide fields based on requisition type
    function updateFields() {
        var requisitionType = $('#id_requisition_type').val();
        if (requisitionType == 'store') {
            $('.location-field').show();
            $('.supplier-field').hide();
        } else if (requisitionType == 'purchase') {
            $('.location-field').hide();
            $('.supplier-field').show();
        }
    }

    // Call updateFields when the page loads
    updateFields();

    // Call updateFields whenever the requisition type changes
    $('#id_requisition_type').change(updateFields);
});
</script>

<script src="{% static 'assets/js/apps/inventory_app/item/requisition/load-items-script.js' %}"></script>
<script src="{% static 'assets/js/apps/inventory_app/item/requisition/load-categories-script.js' %}"></script>
<script src="{% static 'assets/js/apps/inventory_app/item/requisition/update-formset.js' %}"></script>

<script src="{% static 'assets/js/apps/inventory_app/item/requisition/save-draft-submit.js' %}"></script>

<script src="{% static 'assets/js/apps/inventory_app/item/requisition/draft/table.js' %}"></script>

{% endblock extrajs %}