auth_app/urls.py
from django.urls import path
from .views import UserGroupDataView, UserGroupCRUDView, UserGroupDeleteView, PermissionCRUDView, PermissionDataView, \
    RoleCRUDView, RoleDataView, RoleCardView, RoleDetailView, LoginView, LogoutView

app_name = 'auth_app'

urlpatterns = [

    # AUTHENTICATION URLS
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),

    # USER GROUPS URLS
    path('api/usergroup/', UserGroupCRUDView.as_view(), name='usergroup'),
    path('ajax_datatable/usergroup/', UserGroupDataView.as_view(), name='usergroup_data'),
    # path('ajax_datatable/usergroup/', ajax_datatable_views.UserGroupAjaxDatatableView.as_view(),
    #      name="ajax_datatable_usergroups"),
    path('api/usergroup/delete/', UserGroupDeleteView.as_view(), name='usergroup_delete'),

    # PERMISSIONS URLS
    path('api/permission/', PermissionCRUDView.as_view(), name='permission'),
    path('ajax_datatable/permission/', PermissionDataView.as_view(), name='permission_data'),

    # ROLES URLS
    path('api/role/', RoleCRUDView.as_view(), name='role'),
    path('ajax_datatable/role/', RoleDataView.as_view(), name='role_data'),
    path('ajax_card/role/', RoleCardView.as_view(), name='ajax_card-role_data'),
    path('role/view/<int:id>/', RoleDetailView.as_view(), name='role_detail'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('auth_app.urls')),
                  path('', include('dashboard_app.urls')),
                  path('', include('hr_app.urls')),
                  path('', include('inventory_app.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

auth_app/forms.py
from django import forms
from .constants import MODEL_NAMES
from django.contrib.contenttypes.models import ContentType
from .models import AppGroup, Role, Permission


class UserGroupCreateForm(forms.ModelForm):
    parent = forms.ModelChoiceField(queryset=AppGroup.objects.all(), required=False, widget=forms.Select(
        attrs={'data-dropdown-parent': '#userGroupModal', 'data-placeholder': 'Select a Parent Group'}))

    class Meta:
        model = AppGroup
        fields = ['name', 'description', 'parent', 'status']  # Include all relevant fields

    def __init__(self, *args, **kwargs):
        super(UserGroupCreateForm, self).__init__(*args, **kwargs)

        STATUS_CHOICES = [
            ('active', 'Active'),
            ('inactive', 'Inactive'),
            ('locked', 'Locked'),
        ]
        self.fields['status'].widget = forms.Select(choices=STATUS_CHOICES,
                                                    attrs={'data-dropdown-parent': '#userGroupModal'})

    def clean_name(self):
        group_name = self.cleaned_data['name']
        # Exclude the current instance from the exists query
        if AppGroup.objects.exclude(pk=self.instance.pk).filter(name=group_name).exists():
            raise forms.ValidationError('Group with this name already exists.')
        return group_name


class ContentTypeChoiceField(forms.ModelChoiceField):
    def label_from_instance(self, obj):
        # Use your dictionary to get the friendly name for the model
        return MODEL_NAMES.get(f'{obj.app_label} | {obj.model}', str(obj))


class PermissionForm(forms.ModelForm):
    content_type = ContentTypeChoiceField(
        queryset=ContentType.objects.exclude(app_label__in=['auth', 'contenttypes', 'sessions', 'admin', 'guardian']),
        required=False,
        widget=forms.Select(
            attrs={'data-dropdown-parent': '#userPermissionModal', 'data-placeholder': 'Select a Module'})
    )

    class Meta:
        model = Permission
        fields = ['name', 'description', 'content_type']

    def clean(self):
        cleaned_data = super().clean()
        # Add any custom validation here
        return cleaned_data


class RoleForm(forms.ModelForm):
    class Meta:
        model = Role
        fields = ['name', 'description', 'permissions']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter a role name'}),
            'permissions': forms.CheckboxSelectMultiple(),
        }

    def __init__(self, *args, **kwargs):
        super(RoleForm, self).__init__(*args, **kwargs)
        self.fields['permissions'].queryset = Permission.objects.all()

auth_app/views.py
from django.contrib.contenttypes.models import ContentType
from django.core.exceptions import ObjectDoesNotExist, ValidationError
from django.core.validators import validate_email
from django.contrib.auth.password_validation import validate_password  # Import for password validation (optional)
from django.db.models import Prefetch
from django.http import JsonResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import AuthenticationForm
from django.utils import timezone
from django.views.generic.edit import FormView
from django.views import View

from .constants import get_model_name  # make sure to import the function
from .forms import UserGroupCreateForm, PermissionForm, RoleForm
from .models import AppGroup, Permission, Role, AppUser, FailedLoginAttempt
from hr_app.models import Employee, EmployeePhoto


# -----------------------------------------------------------------------------------------------
# AUTHENTICATION
# ------------------------------------------------------------------------------------------------
class LoginView(FormView):
    form_class = AuthenticationForm
    template_name = 'auth_app/login/signin.html'
    success_url = '/dashboard/'

    def form_valid(self, form):
        email = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password')

        ip_address = self.request.META.get('REMOTE_ADDR')

        user = authenticate(self.request, username=email, password=password)
        if user is not None:
            login(self.request, user)
            if self.request.headers.get('x-requested-with') == 'XMLHttpRequest':
                return JsonResponse({'success': True})
            else:
                return redirect(self.success_url)
        else:
            print("Authentication failed")  # Debugging statement
            FailedLoginAttempt.objects.create(username=email, timestamp=timezone.now(),
                                              attempt_type="Invalid Credentials", ip_address=ip_address)
            return JsonResponse({'success': False, 'error': 'Invalid credentials.'})

    def form_invalid(self, form):
        email = form.data.get('username')
        password = form.data.get('password')

        ip_address = self.request.META.get('REMOTE_ADDR')

        # Email Validation
        try:
            validate_email(email)
        except ValidationError:
            print("Email validation failed")  # Debugging statement
            FailedLoginAttempt.objects.create(username=email, timestamp=timezone.now(), attempt_type="Invalid E-mail address",
                                              ip_address=ip_address)
            return JsonResponse({'success': False, 'error': 'Enter a valid email address.'})

        # Password Complexity Validation
        try:
            validate_password(password)
        except ValidationError as e:
            print(f"Password validation error: {e}")  # Debugging statement
            FailedLoginAttempt.objects.create(username=email, timestamp=timezone.now(),
                                              attempt_type="Weak Password",
                                              ip_address=ip_address)
            return JsonResponse({'success': False, 'error': 'Password requirements not met.'})

        # This method is called when the form is invalid.
        # If the form is invalid for reasons other than email or password validation,
        # return a general error message.
        return JsonResponse({'success': False, 'error': 'Invalid credentials'})


class LogoutView(View):
    def get(self, request, *args, **kwargs):
        logout(request)
        return HttpResponseRedirect('/login/')  # Redirect to a login page


# -----------------------------------------------------------------------------------------------
# USER GROUP
# ------------------------------------------------------------------------------------------------
class UserGroupCRUDView(View):
    template_name = "auth_app/group/group_list.html"  # Adapt to your template

    def get(self, request, *args, **kwargs):
        form = UserGroupCreateForm()
        context = {
            'form': form,
            # Add any other context variables you need
        }
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        user_group_id = request.POST.get('id')
        name = request.POST.get('name')
        # Add any other fields you need

        if user_group_id:
            user_group = AppGroup.objects.get(id=user_group_id)
            if AppGroup.objects.filter(name__iexact=name).exclude(id=user_group_id).exists():
                self.response = {"message": 'AppGroup with this Name already exists.'}
                return JsonResponse(self.response)
            else:
                form = UserGroupCreateForm(request.POST, instance=user_group)
                success_message = 'AppGroup updated successfully!'
        else:
            if AppGroup.objects.filter(name__iexact=name).exists():
                self.response = {"message": 'AppGroup with this Name already exists.'}
                return JsonResponse(self.response)
            else:
                form = UserGroupCreateForm(request.POST)
                success_message = 'AppGroup created successfully!'

        if form.is_valid():
            form.save()
            self.response = {"message": success_message, "success": True}
            return JsonResponse(self.response)

        context = {
            'form': form,
            # Add any other context variables you need
        }
        return render(request, self.template_name, context)


class UserGroupDataView(View):
    def get(self, request, *args, **kwargs):
        # Query all data
        data = AppGroup.objects.all()

        STATUS_CHOICES_DICT = {
            'active': '<span class="badge bg-soft-success p-1 text-success">Active</span>',
            'inactive': '<span class="badge bg-soft-warning p-1 text-warning">Inactive</span>',
            'locked': '<span class="badge bg-soft-danger p-1 text-danger">Locked</span>',
        }

        # STATUS_CHOICES_DICT = {
        #     'active': '<div class="text-success">Active</div>',
        #     'inactive': '<div class="text-warning">Inactive</div>',
        #     'locked': '<div class="text-danger">Locked</div>',
        # }

        # Format the data for DataTables
        data_for_datatables = [{
            'id': usergroup.id,
            'name': usergroup.name,
            'parent': usergroup.parent.name if usergroup.parent else None,  # Use the parent's name
            'parent_id': usergroup.parent.id if usergroup.parent else None,  # Use the parent's ID
            'description': usergroup.description,
            'status': usergroup.status,
            'status_display': STATUS_CHOICES_DICT.get(usergroup.status,
                                                      '<span class="badge badge-secondary">Unknown</span>'),
        } for usergroup in data]

        # Return the data
        return JsonResponse({
            'draw': int(request.GET.get('draw', 1)),  # The draw counter for DataTables
            'recordsTotal': len(data_for_datatables),  # The total number of records
            'recordsFiltered': len(data_for_datatables),  # The number of records after filtering
            'data': data_for_datatables,  # The data to display
        })


class UserGroupDeleteView(View):
    def post(self, request, *args, **kwargs):
        # Get the IDs from the request
        ids = request.POST.getlist('ids[]')

        # Delete the AppGroup objects with the given IDs
        AppGroup.objects.filter(id__in=ids).delete()

        # Return a success response with a message
        return JsonResponse({
            'success': True,
            'message': 'Selection have been successfully deleted!'
        })


# -----------------------------------------------------------------------------------------------
# END USER GROUP
# ------------------------------------------------------------------------------------------------


# -----------------------------------------------------------------------------------------------
# PERMISSIONS
# ------------------------------------------------------------------------------------------------

class PermissionCRUDView(View):
    template_name = "auth_app/permission/permission_list.html"  # Adapt to your template

    def get(self, request, *args, **kwargs):
        form = PermissionForm()
        context = {
            'form': form,
            # Add any other context variables you need
        }
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        permission_id = request.POST.get('id')
        name = request.POST.get('name')
        # Add any other fields you need

        if permission_id:
            permission = Permission.objects.get(id=permission_id)
            if Permission.objects.filter(name__iexact=name).exclude(id=permission_id).exists():
                self.response = {"message": 'Permission with this Name already exists.'}
                return JsonResponse(self.response)
            else:
                form = PermissionForm(request.POST, instance=permission)
                success_message = 'Permission updated successfully!'
        else:
            if Permission.objects.filter(name__iexact=name).exists():
                self.response = {"message": 'Permission with this Name already exists.'}
                return JsonResponse(self.response)
            else:
                form = PermissionForm(request.POST)
                success_message = 'Permission created successfully!'

        if form.is_valid():
            form.save()
            self.response = {"message": success_message, "success": True}
            return JsonResponse(self.response)

auth_app/templates/auth_app/role/includes/card.html
{% for role in roles %}
<div class="col-xl-4 col-lg-6 col-md-6">
    <div class="card">
      <div class="card-body">
        <div class="d-flex justify-content-between mb-2">
          <h6 class="fw-normal">Total {{ role.total_users }} users</h6>
          <ul class="list-unstyled d-flex align-items-center avatar-group mb-0">
            <li data-bs-toggle="tooltip" data-popup="tooltip-custom" data-bs-placement="top" title="Vinnie Mostowy" class="avatar avatar-sm pull-up">
              <img class="rounded-circle" src="../../assets/img/avatars/5.png" alt="Avatar">
            </li>
            <li data-bs-toggle="tooltip" data-popup="tooltip-custom" data-bs-placement="top" title="Allen Rieske" class="avatar avatar-sm pull-up">
              <img class="rounded-circle" src="../../assets/img/avatars/12.png" alt="Avatar">
            </li>
            <li data-bs-toggle="tooltip" data-popup="tooltip-custom" data-bs-placement="top" title="Julee Rossignol" class="avatar avatar-sm pull-up">
              <img class="rounded-circle" src="../../assets/img/avatars/6.png" alt="Avatar">
            </li>
            <li data-bs-toggle="tooltip" data-popup="tooltip-custom" data-bs-placement="top" title="Kaith D'souza" class="avatar avatar-sm pull-up">
              <img class="rounded-circle" src="../../assets/img/avatars/15.png" alt="Avatar">
            </li>
            <li data-bs-toggle="tooltip" data-popup="tooltip-custom" data-bs-placement="top" title="John Doe" class="avatar avatar-sm pull-up">
              <img class="rounded-circle" src="../../assets/img/avatars/1.png" alt="Avatar">
            </li>
          </ul>
        </div>
        <div class="d-flex justify-content-between align-items-end">
          <div class="role-heading">
            <h4 class="mb-1">{{ role.name }}</h4>
            <a href="javascript:;" data-bs-toggle="modal" data-bs-target="#addRoleModal" class="role-edit-modal"><small>Edit Role</small></a>
          </div>
          <a href="javascript:void(0);" class="text-muted"><i class="bx bx-copy"></i></a>
        </div>
      </div>
    </div>
</div>
{% endfor %}

auth_app/templates/auth_app/role/includes/form.html
{% load static %}
{% load widget_tweaks %}
<div class="modal fade" id="addRoleModal" data-backdrop="static" data-keyboard="false" tabindex="-1" aria-hidden="true">
  <div class="modal-dialog modal-fullscreen modal-dialog-centered modal-add-new-role"><!-- style="max-width: 1350px;"-->
    <div class="modal-content p-2 p-md-4">
      <div class="modal-body scroll-y mx-5 my-7">
        <!-- Add role form -->
        <form method="post" action="{% url 'auth_app:role' %}" id="RoleForm" class="row g-3 fv-plugins-bootstrap5 fv-plugins-framework" novalidate="novalidate">
          {% csrf_token %}
          <!--begin::Heading-->
            <div class="mb-13 text-left mb-3">
                <!--begin::Title-->
                <h2 class="form-title mb-3">Create Role</h2>
                <!--end::Title-->
            </div>
            <!--end::Heading-->
             <input type="hidden" name="id" value="{{ role.id }}">
          <div class="col-12">
          <!--begin::Input group-->
            <div class="row g-9 mb-8">
                <!--begin::Col-->
                <div class="col-md-6 fv-row">
                    <label class="required fs-6 fw-semibold mb-2">Role</label>
                    {% render_field form.name class="form-control" %}
                </div>
                <!--end::Col-->

                <!--begin::Col-->
                <div class="col-md-6 fv-row">
                    <label class="required fs-6 fw-semibold mb-2">Description</label>
                    {% render_field form.description class="form-control" rows="1" %}
                </div>
                <!--end::Col-->
            </div>
            <!--end::Input group-->
          </div>
        <div class="form-group col-md-12">
          <div class="col-12">
            <label class="required fs-6 fw-semibold mb-2">Permissions</label>
            <div class="form-check mb-2">
                <input class="form-check-input" type="checkbox" id="check_all">
                <label class="form-check-label" for="check_all">Check All</label>
            </div>
            <!-- Permission table -->
            <div class="table-responsive"   style="overflow-y: auto; height: 500px;">

            <table class="table table-striped table-hover rounded">
                <thead>
                    <tr>
                        <th class="th text-left p-3">Module Name</th>
                        <th class="th text-left p-3">Permissions</th>
                    </tr>
                </thead>
                <tbody>
                    {% for content_type, module_name in content_types.items %}
                    <tr>
                        <td class="td p-3">{{ module_name }}</td>
                        <td class="td p-3">
                            <div class="flex flex-wrap gap-2">
                                {% for permission in content_type.auth_app_permissions.all %}
                                <div class="form-check form-check-inline mr-2">
                                    <input class="form-check-input border border-gray-500 rounded" type="checkbox" id="{{ permission.id }}" name="permissions" value="{{ permission.id }}">
                                    <label class="form-check-label" for="{{ permission.id }}">
                                        {{ permission.name }}
                                    </label>
                                </div>
                                {% endfor %}
                            </div>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>


            <!-- Permission table -->
          </div>
           <!--begin::Actions-->
            <div class="text-left mt-5">
                <button type="button" class="btn btn-sm btn-100 btn-warning custom-form-action-button me-3" data-cancel-action="cancel">Discard</button>
                <button type="submit" class="btn btn-sm btn-100 btn-primary custom-form-action-button" id="role-submit-button" data-submit-action="submit">
                    <span class="indicator-label">Submit</span>
                    <span class="indicator-progress">Please wait...
                    <span class="spinner-border spinner-border-sm align-middle ms-2"></span></span>
                </button>
            </div>
            <!--end::Actions-->
        </div>
    	<input type="hidden">
    	</form>
        <!--/ Add role form -->
      </div>
    </div>
  </div>
</div>

auth_app/templates/auth_app/role/includes/modal.html
{% load static %}
{% load widget_tweaks %}
<div class="modal fade" id="RoleModal" tabindex="-1" aria-hidden="true">
  <div class="modal-dialog modal-simple modal-simple modal-dialog-centered modal-add-new-role" style="max-width: 1250px;">
    <div class="modal-content p-3 p-md-5">
      <div class="modal-body">
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        <div class="text-center mb-4">
          <h3 class="role-title">Add New Role</h3>
          <p>Set role permissions</p>
        </div>
        <!-- Add role form -->
        <div class="row">
   <div class="col-md-12">
      <div class="box box-primary">
         <div class="box-header">
            <h4 class="box-title">Create Role</h4>
         </div>
         <div class="box-body ">
            <form class="form" method="post" action="">
    {% csrf_token %}
    <div class="row">
        <div class="form-group col-md-6">
            <label for="{{ form.name.id_for_label }}">Name</label>
            {% render_field form.name class="form-control" placeholder="Enter a role name" tabindex="-1" %}
        </div>

        <div class="form-group col-md-6">
            <label for="{{ form.description.id_for_label }}">Description</label>
            {% render_field form.description class="form-control" rows="1" placeholder="Enter role description" tabindex="-1" %}
        </div>
        <div class="form-group col-md-12">
            <label for="permissions">Permissions</label>
            <div class="form-check">
                <input class="form-check-input" type="checkbox" id="check_all">
                <label class="form-check-label" for="check_all">Check All</label>
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <table class="table table-bordered">
                        <thead>
                            <tr>
                                <th>Module Name</th>
                                <th>View</th>
                                <th>Create</th>
                                <th>Edit</th>
                                <th>Delete</th>
                                <th>Select All</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for content_type, friendly_name in content_types.items %}
                                <tr class="module_checkbox">
                                    <td>{{ friendly_name }}</td>
                                    {% for permission in content_type.auth_app_permissions.all %}
                                        <td>
                                            <div class="form-check">
                                                <input class="form-check-input" type="checkbox" name="permissions" id="{{ content_type.name }}{{ permission.name }}" value="{{ permission.id }}">

                                            </div>
                                        </td>
                                    {% endfor %}
                                    <td>
                                        <div class="form-check">
                                            <input class="form-check-input" type="checkbox" id="select_all_{{ content_type.name }}">
                                            <label class="form-check-label" for="select_all_{{ content_type.name }}">Select All</label>
                                        </div>
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

         </div>
      </div>
   </div>
</div>
        <!--/ Add role form -->
      </div>
    </div>
  </div>
</div>

auth_app/templates/auth_app/role/includes/role_list(group and permission table).html
{% extends "base.html" %}
{% load static %}
{% load widget_tweaks %}
{% block title %} Roles {% endblock title %}

{% block content %}

<div class="d-flex justify-content-between align-items-center flex-wrap mb-4 gap-3">
    <div class="d-flex flex-column">
        <h3>Roles</h3>
        <p class="text-primary mb-0">Administrator Dashboard</p>
    </div>
    <div class="d-flex justify-content-between align-items-center rounded flex-wrap gap-3">
        <div class="form-check form-switch mb-0 iq-status-switch">
            <input class="form-check-input iq-status" type="checkbox" id="iq-switch" checked="">
            <label class="form-check-label iq-reset-status" for="iq-switch">
                Online
            </label>
        </div>
        <div class="form-group mb-0">
            <select class="select2-basic-single form-control" name="state" style="width: 100%;">
                <option >Past 30 Days</option>
                <option >Past 60 Days</option>
                <option >Past 90 Days</option>
                <option >Past 1 year</option>
                <option >Past 2 year</option>
            </select>
        </div>
        <div class="form-group mb-0">
            <input type="text" name="start" class="form-control range_flatpicker flatpickr-input active" placeholder="24 Jan 2022 to 23 Feb 2022" readonly="readonly">
        </div>
        <button type="button" class="btn btn-primary">Analytics</button>
    </div>
</div>

<div class="container-fluid">
    <div class="card card-block card-stretch card-height">
        <nav class="tab-bottom-bordered">
            <div class="mb-0 nav nav-tabs justify-content-around" id="nav-tab1" role="tablist">
                <button class="nav-link py-3 active" id="role-nav-tab" data-bs-toggle="tab" data-bs-target="#role-nav" type="button" role="tab" aria-controls="role-nav" aria-selected="true">Role</button>
                <button class="nav-link py-3" id="permission-nav-tab" data-bs-toggle="tab" data-bs-target="#permission-nav" type="button" role="tab" aria-controls="permission-nav" aria-selected="false" tabindex="-1">Permission</button>
                <button class="nav-link py-3" id="group-nav-tab" data-bs-toggle="tab" data-bs-target="#group-nav" type="button" role="tab" aria-controls="group-nav" aria-selected="false" tabindex="-1">Group</button>
            </div>
        </nav>
        <div class="tab-content iq-tab-fade-up" id="nav-tabContent">
            <div class="tab-pane fade show active" id="role-nav" role="tabpanel" aria-labelledby="role-nav-tab">
                <div class="card-header">
                    <div class="card-toolbar">
                        <button type="button" id="add-role" class="btn btn-sm custom-form-action-button btn-primary me-2" data-bs-toggle="modal" data-bs-backdrop="static" data-bs-keyboard="false" data-bs-target="#addRoleModal">Add Role</button>
                        <button type="button" class="btn btn-sm btn-info custom-form-action-button me-2">Go Back</button>
                        <button type="button" class="btn btn-sm custom-form-action-button btn-info me-2">Refresh</button>
                    </div>
                </div>

                <div class="card-body card-scroll h-100px">
                    {% include 'auth_app/role/includes/role_card.html' %}
<!--                  {% include 'auth_app/role/includes/pi-table.html' %}-->
                </div>
            </div>
            <div class="tab-pane fade" id="permission-nav" role="tabpanel" aria-labelledby="permission-nav-tab">

                <div class="card-header">
                    <div class="card-toolbar">
                        <a href="{% url 'auth_app:permission'%}" type="button" class="btn btn-sm btn-info custom-form-action-button me-2">Permission Page</a>
                        <button type="button" class="btn btn-sm custom-form-action-button btn-info me-2">Refresh</button>
                    </div>
                </div>

                <div class="card-body card-scroll h-150px">
                  {% include 'auth_app/permission/includes/table.html' %}
                </div>
               
            </div>
            <div class="tab-pane fade" id="group-nav" role="tabpanel" aria-labelledby="group-nav-tab">
                <div class="card-header">
                    <div class="card-toolbar">
                        <a href="{% url 'auth_app:usergroup'%}" type="button" class="btn btn-sm btn-info custom-form-action-button me-2">Group Page</a>
                        <button type="button" class="btn btn-sm custom-form-action-button btn-info me-2">Refresh</button>
                    </div>
                </div>
                <div class="card-body card-scroll h-150px">
                  {% include 'auth_app/group/includes/table.html' %}
                </div>
            </div>
        </div>
    </div>
</div>

{% include 'auth_app/role/includes/form.html' %}
{% include 'auth_app/role/includes/modal.html' %}
{% endblock content %}



{% block extrajs %}
<!--Role Scripts -->

<script src="{% static 'assets/js/apps/auth_app/role/checkbox_handler.js' %}"></script>
<script src="{% static 'assets/js/apps/auth_app/role/submit_form.js' %}"></script>
<script src="{% static 'assets/js/apps/auth_app/role/table.js' %}"></script>
<script src="{% static 'assets/js/apps/auth_app/group/table_view.js' %}"></script>
<script src="{% static 'assets/js/apps/auth_app/permission/table_view.js' %}"></script>

{% endblock extrajs %}

auth_app/templates/auth_app/role/includes/table.html
<div class="table-responsive">
    <table id="roleTable" width="100%" class="table table-hover" data-toggle="data-table">
      <thead>
            <tr>
               <th class="w-5px pe-2"></th>
               <th>Role</th>
               <th>Description</th>
               <th class="text-center w-5px pe-2">Actions</th>
            </tr>
         </thead>
         <tbody></tbody>

    </table>
</div>